blank_issues_enabled: true
contact_links:
  - name: Check the Wiki for existing feature requests
    url: https://github.com/johansan/notebook-navigator/wiki
    about: Please check if your feature request is already listed in our Wiki before creating a new issue.